version: '3.8'

services:
  db:
    image: "postgres:15"
    environment:
      TZ: UTC
      PGTZ: UTC
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
    volumes:
      - "./api/tmp/db:/var/lib/postgresql/data"
  redis:
    image: "redis:5-alpine"
    ports:
      - 6379:6379
    volumes:
      - "./data/redis/:/data"
    command: redis-server
  api:
    build:
      context: ./api
    environment:
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      API_DOMAIN: "localhost:$FRONT_PORT"
      FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
      REDIS_URL: "redis://redis"
    volumes:
      - "./api:/app"
    depends_on:
      - db
    ports:
      - "$API_PORT:$CONTAINER_PORT"
  front:
    build:
      context: ./front
      args:
        WORKDIR: /front
        CONTAINER_PORT: $CONTAINER_PORT
        API_URL: "http://localhost:$API_PORT"
        FIREBASE_API_KEY: $FIREBASE_API_KEY
        FIREBASE_AUTH_DOMAIN: $FIREBASE_AUTH_DOMAIN
        FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
    command: npm run dev
    volumes:
      - "./front:/app"
    ports:
      - "$FRONT_PORT:$CONTAINER_PORT"
      - "24678:24678"
    depends_on:
      - api
