name: Run vitest,cypress,eslint

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: verify
    runs-on: ubuntu-latest

    env:
      FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
      FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
      FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          cd front
          npm install

      - name: verify
        run: |
          cd front
          npm run lint
          npm run test:unit

      - name: Cypress run
        uses: cypress-io/github-action@v5
      - name: Write the cypress.env.json file
        run: |
          echo '${{ secrets.CYPRESS_ENV_CI }}' > cypress.env.json

        with:
          config: baseUrl=http://localhost:3000
          working-directory: front
          wait-on: "http://localhost:3000"
          build: npm run build
          start: npm run start

